import { ref } from 'vue'
import { defineStore } from 'pinia'

const messages = {
  zh: {
    // nav
    navHome: '首页', navRecipe: '型号配方', navHistory: '历史数据', navLive: '即时镜头',
    liveTitle: '即时镜头 / 找点位',
    liveHint: '在此可输入坐标让机械臂移动过去，或用手动引导（hand-guiding）移动，配合即时镜头画面对位，满意后再按机械臂上的 Point 按钮记录点位。',
    liveConnecting: '正在连接镜头...',
    liveError: (e) => `镜头错误：${e}`,
    ipPlaceholder: '机械臂 IP',
    speedLabel: '速度',
    stepLabel: '步进量', tipStepUp: '增加', tipStepDown: '减少',
    useCurrentPoseBtn: '取当前位置', tipUseCurrentPose: '把机械臂当前的坐标填入下面的输入框，方便微调',
    moveBtn: '移动到此坐标', tipMoveHere: '让机械臂移动到上面输入的坐标',
    moveOk: '已到达',
    moveFail: '移动失败',
    // home - top bar
    criticalBanner: '⛔ 应用程序发生严重错误，请重新启动后端程序',
    robotWarningBanner: '⚠️ 检测到机械臂连线中断，请确认是否正在手动操作机械臂',
    viewerBanner: '👁 观察模式 — 仅供查看，无法操作',
    armIp: '机械臂 IP',
    disconnect: '断线', connect: '连线',
    viewerMode: '👁 观察模式', controlMode: '🎮 操控模式',
    recipe: '型号',
    connected: '已连线', disconnected: '未连线',
    // home - workspace
    workstation: '机械臂位置',
    jointsTitle: '关节角度 (J1-J6)',
    poseDisconnected: '🔴 未连线',
    poseNoData: '🟡 无数据（监控未连接）',
    poseApprox: '🟠 近似值（依最近一次移动指令，非即时）',
    poseLive: '🟢 实时',
    // home - camera & step navigation
    liveView: '实时影像',
    captureBtn: '拍照',
    lightOnBtn: '💡 开灯', lightOffBtn: '💡 关灯',
    importPointsBtn: '📥 从机械臂导入点位',
    backBtn: '上一步', nextBtn: '下一步',
    stop: '停止 / 重置',
    statusTitle: '错误 / 状态信息',
    // home - log messages
    alertIp: '请输入机械臂 IP',
    logConnected:    (ip) => `已连线到机械臂 ${ip}`,
    logDisconnected: '已断线',
    logConnFail:     (a, e) => `${a === 'connect' ? '连线' : '断线'}失败: ${e}`,
    logNeedConnect:  '请先连线机械臂',
    logCaptured:     '已拍照',
    logCaptureFail:  (e) => '拍照失败: ' + e,
    logLightFail:    (e) => '灯光切换失败: ' + e,
    logImportFail:   (e) => '导入点位失败: ' + e,
    logNeedCapture:  (label) => `📸 "${label}" 是拍照点，请按"拍照"按钮`,
    logStopped:      '已停止并重置',
    robotStatus_idle: '待机', robotStatus_moving: '运行中', robotStatus_paused: '已暂停',
    robotStatus_error: '错误', robotStatus_disconnected: '未连线',
    confirmDisconnect: '确定要断线吗？',
    confirmDisconnectRunning: '机械臂正在运行中，确定要断线吗？',
    confirmImportPoints: (names) => `在机械臂上发现已记录的点位：${names}。要保存为新配方吗？`,
    promptPointCount: '刚才用手动引导记录了几个点位？（请输入正确数量，输入错误的数字会导致机械臂报警）',
    errInvalidCount: '请输入有效的点位数量（大于 0 的整数）',
    errNoPointsFound: '没有找到符合条件的点位（可能是用了不同的工具坐标系 TCP 记录的）',
    noRecipeSelected: '请先选择一个型号配方',
    tipRecipeDropdown: '点击展开型号配方列表',
    tipConnect: '连线到机械臂，重置所有状态',
    tipDisconnect: '断开与机械臂的连线',
    tipSwitchToViewer: '切换为仅查看模式（无法操作）',
    tipSwitchToControl: '切换为操控模式',
    tipApplyRecipe: '将选择的型号配方设为当前使用',
    tipAddRecipe: '新增一个空白型号配方',
    tipEditRecipe: '编辑此配方',
    tipDeleteRecipe: '永久删除此配方',
    tipSaveRecipe: '储存对当前配方的修改',
    tipCancelRecipe: '取消编辑，恢复原始数据',
    tipSaveAsRecipe: '将当前内容另存为新配方',
    tipCapture: '拍摄一张当前画面的照片',
    tipLight: '手动开关相机灯（拍照时会自动开关，与此按钮无关）',
    tipImportPoints: '导入用手动引导（hand-guiding）在机械臂上记录的点位 P1..Pn，请输入正确的点位数量',
    needCaptureBadge: '需拍照', tipNeedCapture: '此点是拍照点，尚未拍照',
    tipBack: '机械臂移动到上一个点位',
    tipNext: '机械臂移动到下一个点位',
    tipStop: '立刻停止并重置机械臂',
    tipHistoryClear: '清除所有历史纪录（此操作不可恢复）',
    tipFilterTime: '按时间范围筛选纪录',
    tipFilterLevel: '按日志级别筛选纪录',
    toastConnected:  '连线成功',
    toastImportSaved: (name) => `已保存为配方 "${name}"`,
    toastDisconnected: '连线中断',
    toastRecipeApplied: (n) => `已套用：${n}`,
    logRecipeApplied:  (n) => `已套用: ${n}`,
    logRecipeFail:     (e) => `套用失败: ${e}`,
    // recipe page (型号配方 — 1 配方 = 1 物件型号，waypoint danh sách tự do)
    recipeTitle: '型号配方',
    addRecipe: '+ 新增型号',
    colName: '名称', colActions: '操作',
    editBtn: '编辑', deleteBtn: '删除',
    editorTitle: '编辑配方', editingTag: '编辑中',
    fieldName: '名称', fieldSpeed: '速度',
    saveBtn: '储存', cancelBtn: '取消', saveAsBtn: '另存新档',
    errDuplicate: '名称重复',
    errNameRequired: '请先输入名称',
    confirmCancel: '确定取消吗？数据会全部消失',
    confirmDelete: '确定删除这个项目吗？',
    alertSaved: '修改成功',
    recipeNotConnected: '⚠️ 尚未连线机械臂 — 请先到首页连线',
    waypointTableTitle: '点位列表（X, Y, Z, Rx, Ry, Rz）',
    colPoint: '点位名称',
    colCapturePoint: '拍照点',
    capturePointTip: '勾选后，在首页拍照时若机械臂正位于此点，照片会以此点位名称标记',
    capturedAtLabel: (label) => `📸 拍摄于：${label}`,
    addWaypointBtn: '+ 新增点位（记录当前位置）',
    addWaypointTip: '将机械臂目前的实际位置新增为一个点位',
    deleteWaypointTip: '删除此点位',
    moveUpTip: '上移此点位',
    moveDownTip: '下移此点位',
    labelPlaceholder: '点位名称',
    saveCurrentPoseBtn: '更新为当前位置',
    saveCurrentPoseTip: '将机械臂目前的实际位置覆盖到这个点位',
    goToBtn: (label) => `前往 ${label}`,
    goToTip: (label) => `移动机械臂到「${label}」点位以测试`,
    liveReadoutTitle: '机械臂实时状态',
    jogTitle: '微调定位',
    stepLabel: '步距',
    logSaveWaypointOk:   (label) => `已更新「${label}」点位`,
    logSaveWaypointFail: (label, e) => `更新「${label}」失败: ${e}`,
    logGoToFail: (label, e) => `前往「${label}」失败: ${e}`,
    logJogFail:  (e) => '微调失败: ' + e,
    // history page
    historyTitle: '历史纪录', historyClear: '清除全部', historyEmpty: '暂无纪录',
    historyConfirmClear: '确定清除所有纪录吗？',
    historyAll: '全部', historyToday: '今天', history7d: '7天', history30d: '30天',
    historyLevelAll: '全部', historyLevelOk: '成功', historyLevelError: '错误', historyLevelInfo: '信息',
  },
  en: {
    // nav
    navHome: 'Home', navRecipe: 'Recipes', navHistory: 'History', navLive: 'Live Camera',
    liveTitle: 'Live Camera / Find Point',
    liveHint: 'Type coordinates to move the robot there, or move it by hand-guiding — use the live camera view to line things up before pressing the Point button on the robot.',
    liveConnecting: 'Connecting to camera...',
    liveError: (e) => `Camera error: ${e}`,
    ipPlaceholder: 'Robot IP',
    speedLabel: 'Speed',
    stepLabel: 'Step size', tipStepUp: 'Increase', tipStepDown: 'Decrease',
    useCurrentPoseBtn: 'Use current pose', tipUseCurrentPose: "Fill the fields below with the robot's current coordinates for fine-tuning",
    moveBtn: 'Move here', tipMoveHere: 'Move the robot to the coordinates entered above',
    moveOk: 'Reached',
    moveFail: 'Move failed',
    // home - top bar
    criticalBanner: '⛔ Application error — please restart the backend',
    robotWarningBanner: '⚠️ Robot connection lost — are you running a program on the robot?',
    viewerBanner: '👁 Observer Mode — View only, no control',
    armIp: 'Arm IP',
    disconnect: 'Disconnect', connect: 'Connect',
    viewerMode: '👁 Observer', controlMode: '🎮 Control',
    recipe: 'Model',
    connected: 'Connected', disconnected: 'Disconnected',
    // home - workspace
    workstation: 'Robot Position',
    jointsTitle: 'Joint Angles (J1-J6)',
    poseDisconnected: '🔴 Disconnected',
    poseNoData: '🟡 No data (monitor not connected)',
    poseApprox: '🟠 Approx (from last move command, not live)',
    poseLive: '🟢 Live',
    // home - camera & step navigation
    liveView: 'Live Feed',
    captureBtn: 'Capture Image',
    lightOnBtn: '💡 Light On', lightOffBtn: '💡 Light Off',
    importPointsBtn: '📥 Import Points from Robot',
    backBtn: 'Back', nextBtn: 'Next',
    stop: 'Stop / Reset',
    statusTitle: 'Error / Status Log',
    // home - log messages
    alertIp: 'Please enter the arm IP address',
    logConnected:    (ip) => `Connected to arm ${ip}`,
    logDisconnected: 'Disconnected',
    logConnFail:     (a, e) => `${a === 'connect' ? 'Connect' : 'Disconnect'} failed: ${e}`,
    logNeedConnect:  'Please connect to the arm first',
    logCaptured:     'Photo captured',
    logCaptureFail:  (e) => 'Capture failed: ' + e,
    logLightFail:    (e) => 'Light toggle failed: ' + e,
    logImportFail:   (e) => 'Import points failed: ' + e,
    logNeedCapture:  (label) => `📸 "${label}" is a Capture Point — press the Capture Image button`,
    logStopped:      'Stopped and reset',
    robotStatus_idle: 'Idle', robotStatus_moving: 'Moving', robotStatus_paused: 'Paused',
    robotStatus_error: 'Error', robotStatus_disconnected: 'Disconnected',
    confirmDisconnect: 'Are you sure you want to disconnect?',
    confirmDisconnectRunning: 'Robot is currently running. Disconnect anyway?',
    confirmImportPoints: (names) => `Found taught point(s) on the robot: ${names}. Save as a new recipe?`,
    promptPointCount: 'How many points were just hand-guided/taught? (Enter the exact number — a wrong number will trigger a robot alarm)',
    errInvalidCount: 'Please enter a valid point count (a whole number greater than 0)',
    errNoPointsFound: 'No matching points found (they may have been taught with a different TCP/tool)',
    noRecipeSelected: 'Select a recipe/model first',
    tipRecipeDropdown: 'Click to open the recipe/model list',
    tipConnect: 'Connect to the robot arm and reset all state',
    tipDisconnect: 'Disconnect from the robot arm',
    tipSwitchToViewer: 'Switch to Observer mode (view only)',
    tipSwitchToControl: 'Switch to Control mode',
    tipApplyRecipe: 'Set the selected recipe/model as active',
    tipAddRecipe: 'Create a new blank recipe',
    tipEditRecipe: "Edit this recipe's parameters",
    tipDeleteRecipe: 'Permanently delete this recipe',
    tipSaveRecipe: 'Save changes to the current recipe',
    tipCancelRecipe: 'Cancel editing and revert changes',
    tipSaveAsRecipe: 'Save current values as a new recipe',
    tipCapture: 'Take a photo of the current camera view',
    tipLight: "Manually toggle the camera light (capture also auto toggles it, independent of this button)",
    tipImportPoints: "Import points P1..Pn that were hand-guided/taught on the robot — enter the exact point count",
    needCaptureBadge: 'Capture needed', tipNeedCapture: 'This point is a Capture Point and has not been photographed yet',
    tipBack: 'Move the robot to the previous waypoint',
    tipNext: 'Move the robot to the next waypoint',
    tipStop: 'Stop immediately and reset the robot',
    tipHistoryClear: 'Delete all history records (cannot be undone)',
    tipFilterTime: 'Filter records by time range',
    tipFilterLevel: 'Filter records by log level',
    toastConnected:  'Connected successfully',
    toastImportSaved: (name) => `Saved as recipe "${name}"`,
    toastDisconnected: 'Connection lost',
    toastRecipeApplied: (n) => `Applied: ${n}`,
    logRecipeApplied:  (n) => `Applied: ${n}`,
    logRecipeFail:     (e) => `Apply failed: ${e}`,
    // recipe page (1 recipe = 1 object/model, with a free-form waypoint list)
    recipeTitle: 'Recipes (Models)',
    addRecipe: '+ New Model',
    colName: 'Name', colActions: 'Actions',
    editBtn: 'Edit', deleteBtn: 'Delete',
    editorTitle: 'Edit Recipe', editingTag: 'Editing',
    fieldName: 'Name', fieldSpeed: 'Speed',
    saveBtn: 'Save', cancelBtn: 'Cancel', saveAsBtn: 'Save as New',
    errDuplicate: 'Name already exists',
    errNameRequired: 'Enter a name first',
    confirmCancel: 'Discard changes?',
    confirmDelete: 'Delete this item?',
    alertSaved: 'Saved successfully',
    recipeNotConnected: '⚠️ Robot not connected — connect it from the Home page first',
    waypointTableTitle: 'Waypoints (X, Y, Z, Rx, Ry, Rz)',
    colPoint: 'Label',
    colCapturePoint: 'Capture Point',
    capturePointTip: 'When checked, capturing an image on Home while the robot is at this waypoint will label the photo with this point\'s name',
    capturedAtLabel: (label) => `📸 Captured at: ${label}`,
    addWaypointBtn: '+ Add Waypoint (capture current pose)',
    addWaypointTip: "Add the robot's current actual position as a new waypoint",
    deleteWaypointTip: 'Delete this waypoint',
    moveUpTip: 'Move this waypoint up',
    moveDownTip: 'Move this waypoint down',
    labelPlaceholder: 'Waypoint label',
    saveCurrentPoseBtn: 'Update to Current Pose',
    saveCurrentPoseTip: "Overwrite this waypoint with the robot's current actual position",
    goToBtn: (label) => `Go ${label}`,
    goToTip: (label) => `Move the robot to the "${label}" waypoint to verify it`,
    liveReadoutTitle: 'Robot Live Status',
    jogTitle: 'Fine Positioning',
    stepLabel: 'Step size',
    logSaveWaypointOk:   (label) => `"${label}" waypoint updated`,
    logSaveWaypointFail: (label, e) => `Update "${label}" failed: ${e}`,
    logGoToFail: (label, e) => `Go to "${label}" failed: ${e}`,
    logJogFail:  (e) => 'Jog failed: ' + e,
    // history page
    historyTitle: 'History', historyClear: 'Clear All', historyEmpty: 'No records yet',
    historyConfirmClear: 'Clear all history?',
    historyAll: 'All', historyToday: 'Today', history7d: '7 Days', history30d: '30 Days',
    historyLevelAll: 'All', historyLevelOk: 'Success', historyLevelError: 'Error', historyLevelInfo: 'Info',
  },
}

export const useLangStore = defineStore('lang', () => {
  const lang     = ref(localStorage.getItem('lang') || 'zh')
  const urlMode  = new URLSearchParams(window.location.search).get('mode')
  const isViewer = ref(urlMode === 'view' ? true : urlMode === 'control' ? false : localStorage.getItem('isViewer') === 'true')

  function setLang(l) {
    lang.value = l
    localStorage.setItem('lang', l)
  }

  function t(key) {
    return messages[lang.value][key] ?? messages['zh'][key] ?? key
  }

  return { lang, setLang, t, isViewer }
})
